"""Code Review Agent for ADK 2.0 Bug Triage System (Claude Sonnet Maker-Checker Peer Review)."""

from typing import Dict, Any, Optional
from google.adk.agents import Agent
from google.adk.models import Gemini
from google.genai import types

from app.config import Config
from app.tools.review_tools import review_code_patch_with_claude
from app.models.bug_report import SanitizedBugReport, EnrichmentContext
from app.observability.logger import StructuredLogger
from app.observability.tracing import execute_tool_with_observability

REVIEW_AGENT_CONSTITUTION = """
You are the Independent Code Review Agent (Critic/Checker) powered by Claude Sonnet.
Core Responsibilities:
1. Conduct an unbiased, cross-model peer review on patches and reproduction tests generated by Gemini 3.1 Pro.
2. Audit security vulnerabilities: Null pointers (CWE-476), SQL injection (CWE-89), input validation (CWE-20).
3. Validate API contracts, backward compatibility, and edge-case handling.
4. Issue a formal verdict ('APPROVED' or 'CHANGES_REQUESTED') and structured quality score before pull requests are raised.
"""

code_review_agent = Agent(
    name="code_review_agent",
    model=Gemini(
        model=Config.FAST_MODEL,
        retry_options=types.HttpRetryOptions(attempts=3),
    ),
    instruction=REVIEW_AGENT_CONSTITUTION.strip(),
    tools=[review_code_patch_with_claude],
)

class CodeReviewAgentRunner:
    """Wrapper runner executing Independent Code Review with full OpenTelemetry and Cloud Logging."""
    
    def __init__(self, logger: Optional[StructuredLogger] = None):
        self.logger = logger or StructuredLogger("CodeReviewAgent")
        self.agent = code_review_agent

    def review_patch(
        self,
        sanitized_report: SanitizedBugReport,
        enrichment_context: EnrichmentContext,
        diff_patch: str,
        patch_explanation: str,
        reproduction_test_code: str,
        request_id: str = "req-001"
    ) -> Dict[str, Any]:
        """Runs unbiased peer code review with full structured tracing."""
        primary_file = enrichment_context.affected_files[0] if enrichment_context.affected_files else "app/services/payment_checkout.py"
        
        return execute_tool_with_observability(
            agent_name="CodeReviewAgent",
            tool_name="review_code_patch_with_claude",
            tool_fn=lambda args: review_code_patch_with_claude(**args),
            args={
                "issue_id": sanitized_report.issue_id,
                "target_file_path": primary_file,
                "diff_patch": diff_patch,
                "patch_explanation": patch_explanation,
                "reproduction_test_code": reproduction_test_code,
                "source_context": None,
            },
            request_id=request_id,
            logger=self.logger,
        )
